service: styled

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  createRecord:
    handler: functions/create.createRecord
    name: ${self:provider.stage}-createRecord
    description: Puts new requests for records in SQS and stores them in DynamoDB
    memorySize: 512
    timeout: 10
    reservedConcurrency: 5
    events:
      - http:
          path: records
          method: post
          cors: true

resources:
  Resources:
    RecordsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
